/* Generated by loom. */
import { createAccordion } from "./recipes/accordion/accordion.js";
import { createCombobox } from "./recipes/combobox/combobox.js";
import { createCommandPalette } from "./recipes/command-palette/command-palette.js";
import { createDatePicker } from "./recipes/date-picker/date-picker.js";
import { createDialog } from "./recipes/dialog/dialog.js";
import { createDrawer } from "./recipes/drawer/drawer.js";
import { createDropdown } from "./recipes/dropdown/dropdown.js";
import { createPagination } from "./recipes/pagination/pagination.js";
import { createPopover } from "./recipes/popover/popover.js";
import { createSelectCustom } from "./recipes/select-custom/select-custom.js";
import { createSheet } from "./recipes/sheet/sheet.js";
import { createTable } from "./recipes/table/table.js";
import { createTabs } from "./recipes/tabs/tabs.js";
import { createToast } from "./recipes/toast/toast.js";
import { createTooltip } from "./recipes/tooltip/tooltip.js";

const controllers = {
  "accordion": createAccordion,
  "combobox": createCombobox,
  "command-palette": createCommandPalette,
  "date-picker": createDatePicker,
  "dialog": createDialog,
  "drawer": createDrawer,
  "dropdown": createDropdown,
  "pagination": createPagination,
  "popover": createPopover,
  "select-custom": createSelectCustom,
  "sheet": createSheet,
  "table": createTable,
  "tabs": createTabs,
  "toast": createToast,
  "tooltip": createTooltip,
};

function initNode(node) {
  if (!node) {
    return;
  }

  const name = node.getAttribute?.("data-ui");

  if (name && controllers[name]) {
    controllers[name](node);
  }

  if (!node.querySelectorAll) {
    return;
  }

  for (const [controllerName, factory] of Object.entries(controllers)) {
    node.querySelectorAll(`[data-ui="${controllerName}"]`).forEach((element) => factory(element));
  }
}

export function init(root = typeof document === "undefined" ? null : document) {
  if (!root) {
    return;
  }

  if (typeof document !== "undefined" && root !== document) {
    initNode(root);
  }

  if (!root.querySelectorAll) {
    return;
  }

  for (const [name, factory] of Object.entries(controllers)) {
    root.querySelectorAll(`[data-ui="${name}"]`).forEach((element) => factory(element));
  }
}

if (typeof document !== "undefined") {
  const start = () => {
    init(document);
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start, { once: true });
  } else {
    start();
  }
}

export { controllers };
