// loom explain <component> — human-and-agent-readable explanation of a component

import { existsSync } from "node:fs";
import { join } from "node:path";
import { log } from "../utils/logger";
import { configExists, readConfig } from "../utils/config";
import { getRegistryPath } from "../utils/fs";
import { loadManifest, type Manifest } from "../manifest";

const BOLD = "\x1b[1m";
const RESET = "\x1b[0m";
const CYAN = "\x1b[36m";
const DIM = "\x1b[2m";
const YELLOW = "\x1b[33m";
const GREEN = "\x1b[32m";
const RED = "\x1b[31m";

export async function explain(args: string[]): Promise<void> {
  if (args.includes("--help") || args.includes("-h")) {
    log.heading("loom explain <component>");
    log.blank();
    console.log("Human-and-agent-readable explanation of a component.");
    log.blank();
    console.log("Options:");
    log.table([
      ["--json", "Output as structured JSON"],
    ]);
    return;
  }

  const name = args.find((a) => !a.startsWith("-"));
  if (!name) {
    log.error("No component specified. Usage: loom explain <component>");
    process.exit(1);
  }

  const jsonMode = args.includes("--json");
  const manifest = await findManifest(name);

  if (!manifest) {
    log.error(`Component '${name}' not found in project or registry.`);
    process.exit(1);
  }

  if (jsonMode) {
    console.log(JSON.stringify(buildExplanation(manifest), null, 2));
    return;
  }

  printExplanation(manifest);
}

async function findManifest(name: string): Promise<Manifest | null> {
  const cwd = process.cwd();

  if (configExists(cwd)) {
    const config = await readConfig(cwd);
    const outputDir = join(cwd, config.output_dir);
    for (const layer of ["primitives", "recipes", "patterns"]) {
      const path = join(outputDir, layer, name, `${name}.manifest.json`);
      if (existsSync(path)) return loadManifest(path);
    }
  }

  const registryPath = getRegistryPath();
  for (const layer of ["primitives", "recipes", "patterns"]) {
    const path = join(registryPath, layer, name, `${name}.manifest.json`);
    if (existsSync(path)) return loadManifest(path);
  }

  return null;
}

interface Explanation {
  name: string;
  description: string;
  purpose: string;
  anatomy: string[];
  states: string;
  variants: string;
  keyboard: string[];
  accessibility: string[];
  safe_to_modify: string[];
  do_not_remove: string[];
  files: Record<string, string>;
}

function buildExplanation(m: Manifest): Explanation {
  // Build anatomy tree
  const anatomy: string[] = [];
  anatomy.push(`[data-ui="${m.name}"]  Root container <${m.anatomy.tag}>`);

  if (m.slots) {
    for (const [slotName, slot] of Object.entries(m.slots)) {
      const req = slot.required ? "(required)" : "(optional)";
      const hint = slot.tag_hint ? ` <${slot.tag_hint}>` : "";
      const desc = slot.description ? ` — ${slot.description}` : "";
      anatomy.push(`  [data-part="${slotName}"]${hint}  ${req}${desc}`);
    }
  }

  // Build states string
  const stateEntries = Object.entries(m.states || {});
  const defaultState = stateEntries.find(([, s]) => s.default);
  const otherStates = stateEntries.filter(([, s]) => !s.default);
  const stateChain = [
    defaultState ? `${defaultState[0]} (default)` : null,
    ...otherStates.map(([n, s]) => s.transient ? `${n} (transient)` : n),
  ].filter(Boolean).join(" → ");

  // Build variants string
  const variantParts: string[] = [];
  for (const [vName, v] of Object.entries(m.variants || {})) {
    variantParts.push(`${vName}: ${v.values.join(" | ")}`);
  }

  // Build keyboard shortcuts
  const keyboard: string[] = [];
  if (m.a11y?.keyboard) {
    for (const [key, action] of Object.entries(m.a11y.keyboard)) {
      keyboard.push(`${key} → ${action}`);
    }
  }

  // Build accessibility notes
  const accessibility: string[] = [];
  if (m.a11y?.role) accessibility.push(`role=${m.a11y.role}`);
  if (m.a11y?.["aria-modal"]) accessibility.push("aria-modal=true");
  if (m.a11y?.focus_trap) accessibility.push("focus-trap");
  if (m.a11y?.escape_closes) accessibility.push("escape-closes");
  if (m.a11y?.return_focus) accessibility.push(`return-focus → ${m.a11y.return_focus}`);
  if (m.a11y?.required_attrs) {
    for (const attr of m.a11y.required_attrs) {
      accessibility.push(attr);
    }
  }

  // Purpose from description + kind
  const kindDesc: Record<string, string> = {
    primitive: "CSS-only visual building block. No JavaScript required.",
    recipe: "Interactive component with JavaScript controller.",
    pattern: "Pre-built composition of primitives and recipes.",
    scaffold: "Full page template generated by the CLI.",
  };

  // Files
  const files: Record<string, string> = {};
  if (m.files.html) files["HTML"] = m.files.html;
  if (m.files.css) files["CSS"] = m.files.css;
  if (m.files.js) files["JS"] = m.files.js;
  files["Spec"] = m.files.manifest;

  return {
    name: m.name,
    description: m.description,
    purpose: kindDesc[m.kind] || "",
    anatomy,
    states: stateChain,
    variants: variantParts.join("  •  "),
    keyboard,
    accessibility,
    safe_to_modify: m.safe_transforms || [],
    do_not_remove: m.unsafe_transforms || [],
    files,
  };
}

function printExplanation(m: Manifest) {
  const ex = buildExplanation(m);
  const cwd = process.cwd();
  let outputDir = "ui";
  if (configExists(cwd)) {
    // Best effort — don't await in sync function
  }

  const layer = m.kind === "primitive" ? "primitives" : m.kind === "recipe" ? "recipes" : "patterns";

  console.log();
  console.log(`${BOLD}${m.name.toUpperCase()}${RESET} — ${m.description}`);
  console.log();

  // Purpose
  console.log(`${CYAN}PURPOSE:${RESET}`);
  console.log(`  ${ex.purpose}`);
  console.log(`  ${m.description}`);
  console.log();

  // Anatomy
  console.log(`${CYAN}ANATOMY:${RESET}`);
  for (const line of ex.anatomy) {
    console.log(`  ${line}`);
  }
  console.log();

  // States
  if (ex.states) {
    console.log(`${CYAN}STATES:${RESET}  ${ex.states}`);
  }

  // Variants
  if (ex.variants) {
    console.log(`${CYAN}VARIANTS:${RESET}  ${ex.variants}`);
  }

  if (ex.states || ex.variants) console.log();

  // Keyboard
  if (ex.keyboard.length > 0) {
    console.log(`${CYAN}KEYBOARD:${RESET}`);
    console.log(`  ${ex.keyboard.join("  •  ")}`);
    console.log();
  }

  // Accessibility
  if (ex.accessibility.length > 0) {
    console.log(`${CYAN}ACCESSIBILITY:${RESET}`);
    for (const a of ex.accessibility) {
      console.log(`  ${a}`);
    }
    console.log();
  }

  // Safe/unsafe
  if (ex.safe_to_modify.length > 0) {
    console.log(`${GREEN}SAFE TO MODIFY:${RESET}  ${ex.safe_to_modify.join(", ")}`);
  }
  if (ex.do_not_remove.length > 0) {
    console.log(`${RED}DO NOT REMOVE:${RESET}   ${ex.do_not_remove.join(", ")}`);
  }
  if (ex.safe_to_modify.length > 0 || ex.do_not_remove.length > 0) console.log();

  // Files
  console.log(`${CYAN}FILES:${RESET}`);
  for (const [label, file] of Object.entries(ex.files)) {
    console.log(`  ${label.padEnd(6)} → ${outputDir}/${layer}/${m.name}/${file}`);
  }
  console.log();
}
