import { existsSync } from "node:fs";
import { join } from "node:path";
import { log } from "../utils/logger";
import { configExists, writeConfig, DEFAULT_CONFIG, type LoomConfig } from "../utils/config";
import { ensureDir, copyDir, copyFile, getRegistryPath, getPackageRoot } from "../utils/fs";
import { generateBundle } from "../utils/bundler";

interface InitOptions {
  theme: string;
  tokensSplit: boolean;
  noCore: boolean;
  dir: string;
}

function parseArgs(args: string[]): InitOptions {
  const opts: InitOptions = {
    theme: "default",
    tokensSplit: false,
    noCore: false,
    dir: "./ui",
  };

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case "--theme":
        opts.theme = args[++i] || "default";
        break;
      case "--tokens-split":
        opts.tokensSplit = true;
        break;
      case "--no-core":
        opts.noCore = true;
        break;
      case "--dir":
        opts.dir = args[++i] || "./ui";
        break;
      case "--help":
      case "-h":
        printHelp();
        process.exit(0);
    }
  }

  return opts;
}

function printHelp() {
  log.heading("loom init");
  log.blank();
  console.log("Initialize a new Loom project in the current directory.");
  log.blank();
  console.log("Options:");
  log.table([
    ["--theme <name>", "Apply a theme during init (default: 'default')"],
    ["--tokens-split", "Keep token files separate instead of single index.css"],
    ["--no-core", "Skip core JS modules (for static-only projects)"],
    ["--dir <path>", "Output to a custom directory (default: './ui')"],
  ]);
}

export async function init(args: string[]): Promise<void> {
  const opts = parseArgs(args);
  const cwd = process.cwd();
  const registryPath = getRegistryPath();
  const outputDir = join(cwd, opts.dir);

  log.heading("Initializing Loom project");

  // Check if already initialized
  if (configExists(cwd)) {
    log.warn("loom.config.json already exists. Use --force to reinitialize.");
    return;
  }

  // 1. Create directory structure
  log.step("Creating directory structure...");
  const dirs = [
    join(outputDir, "tokens"),
    join(outputDir, "base"),
    join(outputDir, "primitives"),
    join(outputDir, "recipes"),
    join(outputDir, "patterns"),
  ];
  if (!opts.noCore) {
    dirs.push(join(outputDir, "core"));
  }
  for (const dir of dirs) {
    ensureDir(dir);
  }

  // 2. Copy tokens
  log.step("Installing design tokens...");
  if (opts.tokensSplit) {
    // Copy individual token files
    await copyDir(join(registryPath, "tokens"), join(outputDir, "tokens"));
  } else {
    // Build a single concatenated tokens file
    const tokenFiles = [
      "palette.css",
      "spacing.css",
      "typography.css",
      "effects.css",
      "motion.css",
      "semantic.css",
      "aliases.css",
    ];

    let combined = "/* Loom Design Tokens — generated by loom init */\n\n";
    for (const file of tokenFiles) {
      const filePath = join(registryPath, "tokens", file);
      if (existsSync(filePath)) {
        const content = await Bun.file(filePath).text();
        // Strip @import lines since we're concatenating
        const stripped = content
          .split("\n")
          .filter((line) => !line.startsWith("@import"))
          .join("\n");
        combined += stripped + "\n";
      }
    }
    await Bun.write(join(outputDir, "tokens", "index.css"), combined);

    // Also copy the index.css with imports for reference
    await copyFile(
      join(registryPath, "tokens", "index.css"),
      join(outputDir, "tokens", "imports.css")
    );
  }

  // 3. Copy base styles
  log.step("Installing base styles...");
  await copyFile(
    join(registryPath, "base", "reset.css"),
    join(outputDir, "base", "reset.css")
  );
  await copyFile(
    join(registryPath, "base", "prose.css"),
    join(outputDir, "base", "prose.css")
  );

  // 4. Copy core JS modules (if not --no-core)
  if (!opts.noCore) {
    log.step("Installing core JS modules...");
    const corePath = join(registryPath, "core");
    if (existsSync(corePath)) {
      await copyDir(corePath, join(outputDir, "core"));
    }
  }

  // 5. Copy theme
  log.step(`Applying theme: ${opts.theme}...`);
  const themePath = join(registryPath, "themes", `${opts.theme}.css`);
  if (existsSync(themePath)) {
    await copyFile(themePath, join(outputDir, "tokens", "theme.css"));
  } else {
    log.warn(`Theme '${opts.theme}' not found, using default.`);
    const defaultThemePath = join(registryPath, "themes", "default.css");
    if (existsSync(defaultThemePath)) {
      await copyFile(defaultThemePath, join(outputDir, "tokens", "theme.css"));
    }
  }

  // 6. Create loom.config.json
  log.step("Creating loom.config.json...");
  const config: LoomConfig = {
    ...DEFAULT_CONFIG,
    theme: opts.theme,
    output_dir: opts.dir,
    tokens_split: opts.tokensSplit,
    include_core: !opts.noCore,
  };
  await writeConfig(config, cwd);

  // 7. Create .loom directory with context placeholder
  log.step("Creating .loom directory...");
  const loomDir = join(cwd, ".loom");
  ensureDir(loomDir);
  await Bun.write(
    join(loomDir, "context.json"),
    JSON.stringify(
      {
        meta: {
          framework: "loom",
          version: "1.0.0",
          theme: opts.theme,
          generated_at: new Date().toISOString(),
          component_count: { primitives: 0, recipes: 0, patterns: 0 },
        },
        protocol: {
          identity: "data-ui",
          part: "data-part",
          state: "data-state",
          variant: "data-variant",
          size: "data-size",
          css_target: "[data-ui='name']",
          state_css: "[data-state='value']",
          theme_attr: "data-theme on <html>",
        },
        components: {},
        rules: {
          use_data_state_not_classes: true,
          always_aria_label_on_icon_buttons: true,
          always_aria_labelledby_on_dialog_panel: true,
          semantic_html_over_div_soup: true,
          tokens_only_no_hardcoded_values: true,
        },
      },
      null,
      2
    ) + "\n"
  );

  // 8. Copy README.md into .loom/
  const readmeSrc = join(getPackageRoot(), "README.md");
  if (existsSync(readmeSrc)) {
    await copyFile(readmeSrc, join(loomDir, "README.md"));
    log.step("Copied README.md into .loom/");
  }

  // Add .loom/ to .gitignore if git repo
  if (existsSync(join(cwd, ".git"))) {
    const gitignorePath = join(cwd, ".gitignore");
    let gitignore = "";
    if (existsSync(gitignorePath)) {
      gitignore = await Bun.file(gitignorePath).text();
    }
    if (!gitignore.includes(".loom/")) {
      gitignore += (gitignore.endsWith("\n") ? "" : "\n") + ".loom/\n";
      await Bun.write(gitignorePath, gitignore);
      log.step("Added .loom/ to .gitignore");
    }
  }

  // 9. Generate initial CSS bundle (tokens + base + theme)
  log.step("Generating CSS bundle...");
  config.bundle = {
    output: `${opts.dir}/loom.bundle.css`,
    auto: true,
    minify: false,
  };
  await writeConfig(config, cwd);
  await generateBundle(cwd);

  log.blank();
  log.success("Loom project initialized!");
  log.blank();
  console.log("  Project structure:");
  log.step(`${opts.dir}/tokens/   — design tokens`);
  log.step(`${opts.dir}/base/     — CSS reset & prose`);
  if (!opts.noCore) {
    log.step(`${opts.dir}/core/     — loom-core.js, api-source.js, utility modules`);
  }
  log.step(`${opts.dir}/primitives/ — CSS-only components`);
  log.step(`${opts.dir}/recipes/   — interactive components`);
  log.step(`${opts.dir}/patterns/  — compositions`);
  log.step(`${opts.dir}/loom.bundle.css — single CSS bundle`);
  log.blank();
  console.log("  Next steps:");
  log.step("loom add button card input   — add components");
  log.step("loom list                    — see available components");
  log.step("loom dev                     — start dev server");
  log.step("loom doctor                  — check project health");
}
