import { generateContext } from "../generator/context";
import {
  appendUniqueLine,
  ensureDir,
  fileExists,
  readTextFile,
  writeJsonFile,
  writeTextFile,
} from "../utils/fs";
import {
  createDefaultConfig,
  formatOutputDir,
  type LoomConfig,
  LOOM_VERSION,
} from "../utils/config";
import { info, success } from "../utils/logger";
import {
  resolvePackagePath,
  resolveRegistryPath,
} from "../utils/paths";

const TOKEN_FILES = [
  "palette.css",
  "semantic.css",
  "aliases.css",
  "spacing.css",
  "typography.css",
  "effects.css",
  "motion.css",
] as const;

const CORE_FILES = [
  "dom.js",
  "events.js",
  "focus.js",
  "motion.js",
  "store.js",
  "utils.js",
] as const;

type InitOptions = {
  dir: string;
  theme: string;
  tokensSplit: boolean;
  includeCore: boolean;
};

export async function initCommand(args: string[], cwd: string): Promise<void> {
  const options = parseInitArgs(args);
  const outputDir = formatOutputDir(options.dir);
  const config = createDefaultConfig({
    version: LOOM_VERSION,
    theme: options.theme,
    outputDir,
    tokensSplit: options.tokensSplit,
    includeCore: options.includeCore,
  });

  await ensureProjectStructure(cwd, config);
  await writeTokens(cwd, config);
  await writeBaseStyles(cwd, config);

  if (config.include_core) {
    await writeCoreModules(cwd, config);
  }

  await writeJsonFile(resolvePackagePath(cwd, "loom.config.json"), config);
  await ensureDir(resolvePackagePath(cwd, ".loom"));
  await writeJsonFile(
    resolvePackagePath(cwd, ".loom", "context.json"),
    generateContext(config),
  );

  if (await fileExists(resolvePackagePath(cwd, ".git"))) {
    await appendUniqueLine(resolvePackagePath(cwd, ".gitignore"), ".loom/");
  }

  success(`Initialized Loom in ${config.output_dir}`);
}

function parseInitArgs(args: string[]): InitOptions {
  const options: InitOptions = {
    dir: "./ui",
    theme: "default",
    tokensSplit: false,
    includeCore: true,
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === "--theme") {
      const value = args[index + 1];
      if (!value) {
        throw new Error("--theme requires a value");
      }
      options.theme = value;
      index += 1;
      continue;
    }

    if (arg === "--tokens-split") {
      options.tokensSplit = true;
      continue;
    }

    if (arg === "--no-core") {
      options.includeCore = false;
      continue;
    }

    if (arg === "--dir") {
      const value = args[index + 1];
      if (!value) {
        throw new Error("--dir requires a value");
      }
      options.dir = value;
      index += 1;
      continue;
    }

    throw new Error(`Unknown option: ${arg}`);
  }

  return options;
}

async function ensureProjectStructure(projectRoot: string, config: LoomConfig): Promise<void> {
  const outputRoot = resolvePackagePath(projectRoot, config.output_dir);
  const directories = [
    outputRoot,
    resolvePackagePath(outputRoot, "tokens"),
    resolvePackagePath(outputRoot, "base"),
    resolvePackagePath(outputRoot, "primitives"),
    resolvePackagePath(outputRoot, "recipes"),
    resolvePackagePath(outputRoot, "patterns"),
  ];

  if (config.include_core) {
    directories.push(resolvePackagePath(outputRoot, "core"));
  }

  for (const directory of directories) {
    await ensureDir(directory);
  }
}

async function writeTokens(projectRoot: string, config: LoomConfig): Promise<void> {
  const outputRoot = resolvePackagePath(projectRoot, config.output_dir);
  const tokensDir = resolvePackagePath(outputRoot, "tokens");
  const tokenContents = await Promise.all(
    TOKEN_FILES.map(async (fileName) => {
      const content = await readTextFile(resolveRegistryPath("tokens", fileName));
      return { fileName, content };
    }),
  );
  const themeCss = await readTextFile(resolveRegistryPath("themes", `${config.theme}.css`));

  if (config.tokens_split) {
    for (const tokenFile of tokenContents) {
      await writeTextFile(resolvePackagePath(tokensDir, tokenFile.fileName), tokenFile.content);
    }

    const imports = [
      "/* Generated by loom init */",
      ...TOKEN_FILES.map((fileName) => `@import "./${fileName}";`),
      '@import "./theme.css";',
      "",
    ].join("\n");

    await writeTextFile(resolvePackagePath(tokensDir, "index.css"), imports);
    await writeTextFile(resolvePackagePath(tokensDir, "theme.css"), themeCss);
    return;
  }

  const bundledCss = [
    "/* Generated by loom init */",
    ...tokenContents.map(({ fileName, content }) => `${banner(fileName)}\n${content}`),
    `${banner("theme.css")}\n${themeCss}`,
    "",
  ].join("\n\n");

  await writeTextFile(resolvePackagePath(tokensDir, "index.css"), bundledCss);
}

async function writeBaseStyles(projectRoot: string, config: LoomConfig): Promise<void> {
  const outputRoot = resolvePackagePath(projectRoot, config.output_dir);
  const baseDir = resolvePackagePath(outputRoot, "base");
  const baseFiles = ["reset.css", "prose.css"] as const;

  for (const fileName of baseFiles) {
    await writeTextFile(
      resolvePackagePath(baseDir, fileName),
      await readTextFile(resolveRegistryPath("base", fileName)),
    );
  }
}

async function writeCoreModules(projectRoot: string, config: LoomConfig): Promise<void> {
  const outputRoot = resolvePackagePath(projectRoot, config.output_dir);
  const coreDir = resolvePackagePath(outputRoot, "core");

  for (const fileName of CORE_FILES) {
    await writeTextFile(
      resolvePackagePath(coreDir, fileName),
      await readTextFile(resolveRegistryPath("core", fileName)),
    );
  }
}

function banner(fileName: string): string {
  return `/* Source: ${fileName} */`;
}

export const testables = {
  parseInitArgs,
};
