import { existsSync } from "node:fs";
import { join } from "node:path";
import { loadManifest } from "../manifest";
import { ensureDir } from "./fs";
import { controllerName } from "./components";
import type { LoomConfig } from "./config";

export async function regenerateLoomInit(
  config: { installed: { recipes: string[] } },
  outputDir: string
): Promise<void> {
  const coreDir = join(outputDir, "core");
  if (!existsSync(coreDir)) return;

  const recipes = config.installed.recipes;
  if (recipes.length === 0) return;

  const imports = recipes
    .map((r) => `import { ${controllerName(r)} } from "../recipes/${r}/${r}.js";`)
    .join("\n");

  const entries = recipes
    .map((r) => `  ${r}: ${controllerName(r)},`)
    .join("\n");

  const content = `// @ui:core loom
// @ui:provides init controllers
// Auto-generated by \`loom add\`. Do not edit manually.

${imports}

const controllers = {
${entries}
};

function init() {
  for (const [name, factory] of Object.entries(controllers)) {
    document.querySelectorAll(\`[data-ui="\${name}"]\`).forEach(factory);
  }
}

// Auto-init on DOM ready
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", init);
} else {
  init();
}

// Re-init on dynamic content (MutationObserver)
const observer = new MutationObserver((mutations) => {
  for (const mutation of mutations) {
    for (const node of mutation.addedNodes) {
      if (node.nodeType !== 1) continue;
      const ui = node.getAttribute?.("data-ui");
      if (ui && controllers[ui]) controllers[ui](node);
      if (node.querySelectorAll) {
        for (const [name, factory] of Object.entries(controllers)) {
          node.querySelectorAll(\`[data-ui="\${name}"]\`).forEach(factory);
        }
      }
    }
  }
});
observer.observe(document.body, { childList: true, subtree: true });

export { init, controllers };
`;

  await Bun.write(join(coreDir, "loom.js"), content);
}

export async function regenerateContext(
  config: { installed: { primitives: string[]; recipes: string[]; patterns: string[] }; theme: string },
  outputDir: string,
  cwd: string
): Promise<void> {
  const components: Record<string, unknown> = {};

  for (const layer of ["primitives", "recipes", "patterns"] as const) {
    for (const name of config.installed[layer]) {
      const manifestPath = join(outputDir, layer, name, `${name}.manifest.json`);
      if (!existsSync(manifestPath)) continue;

      const manifest = await loadManifest(manifestPath);

      const entry: Record<string, unknown> = {
        kind: manifest.kind,
      };

      if (manifest.variants) {
        const variants: Record<string, string[]> = {};
        for (const [key, v] of Object.entries(manifest.variants)) {
          variants[key] = v.values;
        }
        entry.variants = variants;
      }

      if (manifest.slots && Object.keys(manifest.slots).length > 0) {
        entry.slots = Object.keys(manifest.slots);
      }

      if (manifest.states && Object.keys(manifest.states).length > 0) {
        entry.states = Object.keys(manifest.states);
      }

      if (manifest.templates?.html) {
        entry.template = manifest.templates.html;
      }

      if (manifest.safe_transforms?.length > 0) {
        entry.safe_transforms = manifest.safe_transforms;
      }

      if (manifest.files?.js) {
        entry.controller = manifest.files.js;
      }

      components[name] = entry;
    }
  }

  const context = {
    meta: {
      framework: "loom",
      version: "1.0.0",
      theme: config.theme,
      generated_at: new Date().toISOString(),
      component_count: {
        primitives: config.installed.primitives.length,
        recipes: config.installed.recipes.length,
        patterns: config.installed.patterns.length,
      },
    },
    protocol: {
      identity: "data-ui",
      part: "data-part",
      state: "data-state",
      variant: "data-variant",
      size: "data-size",
      css_target: "[data-ui='name']",
      state_css: "[data-state='value']",
      theme_attr: "data-theme on <html>",
    },
    components,
    rules: {
      use_data_state_not_classes: true,
      always_aria_label_on_icon_buttons: true,
      always_aria_labelledby_on_dialog_panel: true,
      semantic_html_over_div_soup: true,
      tokens_only_no_hardcoded_values: true,
    },
  };

  const loomDir = join(cwd, ".loom");
  ensureDir(loomDir);
  await Bun.write(join(loomDir, "context.json"), JSON.stringify(context, null, 2) + "\n");
}
