// @ui:core loom
// @ui:provides init controllers

// Auto-init all recipe controllers found in the DOM.
// Import recipe controllers as they are added to the project.
// This file is regenerated by `loom add` when recipes are installed.

import { createDialog } from "../recipes/dialog/dialog.js";
import { createDrawer } from "../recipes/drawer/drawer.js";
import { createTabs } from "../recipes/tabs/tabs.js";
import { createDropdown } from "../recipes/dropdown/dropdown.js";
import { createAccordion } from "../recipes/accordion/accordion.js";
import { createTooltip } from "../recipes/tooltip/tooltip.js";
import { createToastContainer } from "../recipes/toast/toast.js";
import { createCombobox } from "../recipes/combobox/combobox.js";
import { createCommandPalette } from "../recipes/command-palette/command-palette.js";
import { createTable } from "../recipes/table/table.js";
import { createSelectCustom } from "../recipes/select-custom/select-custom.js";
import { createPopover } from "../recipes/popover/popover.js";
import { createPagination } from "../recipes/pagination/pagination.js";
import { createSheet } from "../recipes/sheet/sheet.js";
import { createDatePicker } from "../recipes/date-picker/date-picker.js";

const controllers = {
  dialog: createDialog,
  drawer: createDrawer,
  tabs: createTabs,
  dropdown: createDropdown,
  accordion: createAccordion,
  tooltip: createTooltip,
  "toast-container": createToastContainer,
  combobox: createCombobox,
  "command-palette": createCommandPalette,
  table: createTable,
  "select-custom": createSelectCustom,
  popover: createPopover,
  pagination: createPagination,
  sheet: createSheet,
  "date-picker": createDatePicker,
};

function init() {
  for (const [name, factory] of Object.entries(controllers)) {
    document.querySelectorAll(`[data-ui="${name}"]`).forEach(factory);
  }
}

// Auto-init on DOM ready
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", init);
} else {
  init();
}

// Re-init on dynamic content (MutationObserver)
const observer = new MutationObserver((mutations) => {
  for (const mutation of mutations) {
    for (const node of mutation.addedNodes) {
      if (node.nodeType !== 1) continue;
      const ui = node.getAttribute?.("data-ui");
      if (ui && controllers[ui]) controllers[ui](node);
      // Also check children
      if (node.querySelectorAll) {
        for (const [name, factory] of Object.entries(controllers)) {
          node.querySelectorAll(`[data-ui="${name}"]`).forEach(factory);
        }
      }
    }
  }
});
observer.observe(document.body, { childList: true, subtree: true });

export { init, controllers };
